# Copyright 2022 VMware, Inc.
#
# This product is licensed to you under the BSD-2 license (the "License").
# You may not use this product except in compliance with the BSD-2 License.
# This product may include a number of subcomponents with separate copyright
# notices and license terms. Your use of these subcomponents is subject to
# the terms and conditions of the subcomponent's license, as noted in the
# LICENSE file.
#
# SPDX-License-Identifier: BSD-2-Clause
run:
  # Lint using Go 1.17, since some linters are disabled by default for Go 1.18
  # until generics are supported.
  # See https://github.com/golangci/golangci-lint/issues/2649
  go: "1.17"

linters:
  disable-all: true
  enable:
    - staticcheck
    - gofmt
    - govet
    - gosimple
    - unused
    - typecheck
    - forbidigo
